### PR TITLE
45 degree slider labels

### PR DESCRIPTION
**Pull request by punkmap**
got a little time at FOSS4G to fix up dem slider labels. still working on chart

### CODE REVIEW

**Comment by NeighborhoodCompass** [comment]
Thanks so much, Tyler.

I'll give it a whirl - see you soon!

John

compass.durhamnc.govhttp://compass.durhamnc.gov
919.560.1647

On May 5, 2016, at 12:41 PM, "punkmap" <notifications@github.com<mailto:notifications@github.com>> wrote:

got a little time at FOSS4G to fix up dem slider labels. still working on chart

---

You can view, comment on, or merge this pull request online at:

  https://github.com/NeighborhoodCompass/2.0/pull/3

Commit Summary
-   ye' blockgroupsofolde
-   45 degree slider labels
-   45 degree slider labels

File Changes
-   M dist/css/main.csshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-0 (2)
-   M dist/data/census.topo.jsonhttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-1 (2)
-   M dist/images/report-logo.pnghttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-2 (0)
-   M dist/index.htmlhttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-3 (4)
-   M dist/index10142015.htmlhttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-4 (4)
-   M dist/index12072015.htmlhttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-5 (4)
-   M dist/index12092015.htmlhttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-6 (4)
-   M dist/js/main.jshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-7 (31)
-   M dist/report.htmlhttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-8 (4)
-   M dist/reportOLD.htmlhttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-9 (4)
-   D node_modules/.bin/bin-version-checkhttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-10 (15)
-   A node_modules/.bin/bin-version-checkhttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-11 (1)
-   D node_modules/.bin/browserslisthttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-12 (15)
-   A node_modules/.bin/browserslisthttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-13 (1)
-   D node_modules/.bin/cleancsshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-14 (15)
-   A node_modules/.bin/cleancsshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-15 (1)
-   D node_modules/.bin/cssohttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-16 (15)
-   A node_modules/.bin/cssohttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-17 (1)
-   D node_modules/.bin/dateformathttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-18 (15)
-   A node_modules/.bin/dateformathttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-19 (1)
-   D node_modules/.bin/dev-iphttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-20 (15)
-   A node_modules/.bin/dev-iphttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-21 (1)
-   D node_modules/.bin/errnohttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-22 (15)
-   A node_modules/.bin/errnohttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-23 (1)
-   D node_modules/.bin/esparsehttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-24 (15)
-   A node_modules/.bin/esparsehttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-25 (1)
-   D node_modules/.bin/esvalidatehttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-26 (15)
-   A node_modules/.bin/esvalidatehttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-27 (1)
-   D node_modules/.bin/executablehttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-28 (15)
-   A node_modules/.bin/executablehttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-29 (1)
-   D node_modules/.bin/expresshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-30 (15)
-   A node_modules/.bin/expresshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-31 (1)
-   D node_modules/.bin/find-versionshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-32 (15)
-   A node_modules/.bin/find-versionshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-33 (1)
-   D node_modules/.bin/foxyhttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-34 (15)
-   A node_modules/.bin/foxyhttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-35 (1)
-   D node_modules/.bin/gifsiclehttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-36 (15)
-   A node_modules/.bin/gifsiclehttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-37 (1)
-   D node_modules/.bin/har-validatorhttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-38 (15)
-   A node_modules/.bin/har-validatorhttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-39 (1)
-   D node_modules/.bin/has-ansihttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-40 (15)
-   A node_modules/.bin/has-ansihttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-41 (1)
-   D node_modules/.bin/image-sizehttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-42 (15)
-   A node_modules/.bin/image-sizehttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-43 (1)
-   D node_modules/.bin/indent-stringhttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-44 (15)
-   A node_modules/.bin/indent-stringhttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-45 (1)
-   D node_modules/.bin/jpegtranhttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-46 (15)
-   A node_modules/.bin/jpegtranhttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-47 (1)
-   D node_modules/.bin/js-yamlhttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-48 (15)
-   A node_modules/.bin/js-yamlhttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-49 (1)
-   D node_modules/.bin/json2yamlhttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-50 (15)
-   A node_modules/.bin/json2yamlhttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-51 (1)
-   D node_modules/.bin/lesschttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-52 (15)
-   A node_modules/.bin/lesschttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-53 (1)
-   D node_modules/.bin/lpad-alignhttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-54 (15)
-   A node_modules/.bin/lpad-alignhttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-55 (1)
-   D node_modules/.bin/lthttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-56 (15)
-   A node_modules/.bin/lthttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-57 (1)
-   D node_modules/.bin/markedhttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-58 (15)
-   A node_modules/.bin/markedhttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-59 (1)
-   D node_modules/.bin/nopthttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-60 (15)
-   A node_modules/.bin/nopthttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-61 (1)
-   D node_modules/.bin/optipnghttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-62 (15)
-   A node_modules/.bin/optipnghttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-63 (1)
-   D node_modules/.bin/pretty-byteshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-64 (15)
-   A node_modules/.bin/pretty-byteshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-65 (1)
-   D node_modules/.bin/rchttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-66 (15)
-   A node_modules/.bin/rchttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-67 (1)
-   D node_modules/.bin/repeatinghttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-68 (15)
-   A node_modules/.bin/repeatinghttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-69 (1)
-   D node_modules/.bin/rimrafhttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-70 (15)
-   A node_modules/.bin/rimrafhttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-71 (1)
-   D node_modules/.bin/seek-bunziphttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-72 (15)
-   A node_modules/.bin/seek-bunziphttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-73 (1)
-   D node_modules/.bin/seek-tablehttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-74 (15)
-   A node_modules/.bin/seek-tablehttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-75 (1)
-   D node_modules/.bin/semverhttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-76 (15)
-   A node_modules/.bin/semverhttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-77 (1)
-   D node_modules/.bin/strip-ansihttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-78 (15)
-   A node_modules/.bin/strip-ansihttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-79 (1)
-   D node_modules/.bin/strip-bomhttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-80 (15)
-   A node_modules/.bin/strip-bomhttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-81 (1)
-   D node_modules/.bin/strip-dirshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-82 (15)
-   A node_modules/.bin/strip-dirshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-83 (1)
-   D node_modules/.bin/strip-indenthttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-84 (15)
-   A node_modules/.bin/strip-indenthttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-85 (1)
-   D node_modules/.bin/strip-json-commentshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-86 (15)
-   A node_modules/.bin/strip-json-commentshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-87 (1)
-   D node_modules/.bin/supports-colorhttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-88 (15)
-   A node_modules/.bin/supports-colorhttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-89 (1)
-   D node_modules/.bin/svgohttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-90 (15)
-   A node_modules/.bin/svgohttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-91 (1)
-   D node_modules/.bin/throttleproxyhttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-92 (15)
-   A node_modules/.bin/throttleproxyhttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-93 (1)
-   D node_modules/.bin/uglifyjshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-94 (15)
-   A node_modules/.bin/uglifyjshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-95 (1)
-   D node_modules/.bin/user-homehttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-96 (15)
-   A node_modules/.bin/user-homehttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-97 (1)
-   D node_modules/.bin/uuidhttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-98 (15)
-   A node_modules/.bin/uuidhttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-99 (1)
-   D node_modules/.bin/weinrehttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-100 (15)
-   A node_modules/.bin/weinrehttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-101 (1)
-   D node_modules/.bin/window-sizehttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-102 (15)
-   A node_modules/.bin/window-sizehttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-103 (1)
-   D node_modules/.bin/yaml2jsonhttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-104 (15)
-   A node_modules/.bin/yaml2jsonhttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-105 (1)
-   T node_modules/bin-version-check/cli.jshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-106 (0)
-   T node_modules/browserslist/cli.jshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-107 (0)
-   T node_modules/clean-css/bin/cleancsshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-108 (0)
-   T node_modules/csso/bin/cssohttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-109 (0)
-   T node_modules/dateformat/bin/cli.jshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-110 (0)
-   D node_modules/decompress/node_modules/.bin/mkdirphttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-111 (15)
-   A node_modules/decompress/node_modules/.bin/mkdirphttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-112 (1)
-   T node_modules/decompress/node_modules/mkdirp/bin/cmd.jshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-113 (0)
-   T node_modules/dev-ip/lib/dev-ip.jshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-114 (0)
-   D node_modules/download/node_modules/.bin/mkdirphttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-115 (15)
-   A node_modules/download/node_modules/.bin/mkdirphttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-116 (1)
-   T node_modules/download/node_modules/mkdirp/bin/cmd.jshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-117 (0)
-   T node_modules/errno/cli.jshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-118 (0)
-   T node_modules/esprima/bin/esparse.jshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-119 (0)
-   T node_modules/esprima/bin/esvalidate.jshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-120 (0)
-   T node_modules/executable/cli.jshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-121 (0)
-   T node_modules/express/bin/expresshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-122 (0)
-   T node_modules/find-versions/cli.jshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-123 (0)
-   T node_modules/foxy/cli.jshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-124 (0)
-   T node_modules/gifsicle/cli.jshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-125 (0)
-   A node_modules/gifsicle/vendor/gifsiclehttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-126 (0)
-   T node_modules/har-validator/bin/har-validatorhttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-127 (0)
-   T node_modules/has-ansi/cli.jshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-128 (0)
-   T node_modules/image-size/bin/image-sizehttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-129 (0)
-   D node_modules/imagemin/node_modules/.bin/mkdirphttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-130 (15)
-   A node_modules/imagemin/node_modules/.bin/mkdirphttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-131 (1)
-   T node_modules/imagemin/node_modules/mkdirp/bin/cmd.jshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-132 (0)
-   T node_modules/indent-string/cli.jshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-133 (0)
-   T node_modules/jpegtran-bin/cli.jshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-134 (0)
-   A node_modules/jpegtran-bin/vendor/jpegtranhttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-135 (0)
-   T node_modules/js-yaml/bin/js-yaml.jshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-136 (0)
-   T node_modules/less/bin/lesschttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-137 (0)
-   T node_modules/localtunnel/bin/clienthttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-138 (0)
-   T node_modules/lpad-align/cli.jshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-139 (0)
-   T node_modules/marked/bin/markedhttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-140 (0)
-   T node_modules/node-uuid/bin/uuidhttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-141 (0)
-   T node_modules/nopt/bin/nopt.jshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-142 (0)
-   T node_modules/optipng-bin/cli.jshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-143 (0)
-   A node_modules/optipng-bin/vendor/optipnghttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-144 (0)
-   T node_modules/pretty-bytes/cli.jshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-145 (0)
-   T node_modules/rc/index.jshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-146 (0)
-   T node_modules/repeating/cli.jshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-147 (0)
-   T node_modules/rimraf/bin.jshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-148 (0)
-   T node_modules/seek-bzip/bin/seek-bunziphttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-149 (0)
-   T node_modules/seek-bzip/bin/seek-bzip-tablehttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-150 (0)
-   T node_modules/semver/bin/semverhttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-151 (0)
-   T node_modules/stream-throttle/bin/throttleproxy.jshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-152 (0)
-   T node_modules/strip-ansi/cli.jshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-153 (0)
-   T node_modules/strip-bom/cli.jshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-154 (0)
-   T node_modules/strip-dirs/cli.jshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-155 (0)
-   T node_modules/strip-indent/cli.jshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-156 (0)
-   T node_modules/strip-json-comments/cli.jshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-157 (0)
-   T node_modules/supports-color/cli.jshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-158 (0)
-   T node_modules/svgo/bin/svgohttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-159 (0)
-   T node_modules/uglify-js/bin/uglifyjshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-160 (0)
-   T node_modules/user-home/cli.jshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-161 (0)
-   T node_modules/weinre/weinrehttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-162 (0)
-   T node_modules/window-size/cli.jshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-163 (0)
-   T node_modules/yamljs/bin/json2yamlhttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-164 (0)
-   T node_modules/yamljs/bin/yaml2jsonhttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-165 (0)
-   M src/less/main.lesshttps://github.com/NeighborhoodCompass/2.0/pull/3/files#diff-166 (1)

Patch Links:
-   https://github.com/NeighborhoodCompass/2.0/pull/3.patch
-   https://github.com/NeighborhoodCompass/2.0/pull/3.diff

**Comment by punkmap** [comment]
Sure thing dudeman! I have some good progress on the histogram too but it's going to take some time.

**Comment by NeighborhoodCompass** [comment]
Awesome, thanks.

I’ve got the neighborhoods swapped out for Census tracts successfully and now I’m pulling together lots of tract data, from the LTDB and HMDA in particular. I’m hoping to use the histogram before May 19, but no worries if that’s not practical – just give me a heads up and I’ll prepare my presentation accordingly!

Thanks as always, Tyler!

John

**Comment by NeighborhoodCompass** [comment]
Changes incorporated from punkmap repo earlier this year.

**Pull request closed without merging**
